spring:
  profiles:
    active: dev
  servlet:
     multipart:
       max-file-size:  10MB
       max-request-size:  20MB
  redis:
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms

token:
    header: Authorization
    secret: abcdefghijklmnopqrstuvwxyz
    expireTime: 30

mybatis-plus:
  mapper-locations:
    - classpath:mapper/*Mapper.xml
    - classpath:mapper/*/*Mapper.xml
  type-aliases-package: com.sixsixsix516.common.model
  configuration:
    map-underscore-to-camel-case: true

xss:
  enabled: true
  excludes: /system/notice/*
  urlPatterns: /system/*,/monitor/*,/tool/*


path:
  project_path: 127.0.0.1:8080/