spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///sun-web?autoReconnect=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT%2B8
    username: root
    password: 1111
  servlet:
     multipart:
       max-file-size:  10MB
       max-request-size:  20MB
  redis:
    database: 4
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms

token:
    header: Authorization
    secret: abcdefghijklmnopqrstuvwxyz
    expireTime: 30

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.sixsixsix516.model.system
  configuration:
    map-underscore-to-camel-case: true

xss:
  enabled: true
  excludes: /system/notice/*
  urlPatterns: /system/*,/monitor/*,/tool/*
